# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Taint
version:      1.04
version_from: Taint.pm
installdirs:  site
requires:
    overload:                      0
    Scalar::Util:                  0
    Test::Builder:                 0
    Test::More:                    0
    Tie::Array:                    0
    Tie::Hash:                     0
    Tie::Scalar:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
